---
train_n_vars: [5, 10, 20]
test_n_vars: [20, 50]
test_n_datasets: 25

data:
  - n_observations_obs: 200      #  
    n_observations_int: 100      #  

    graph:
      - __class__: ErdosRenyi
        edges_per_var: [2.0]     #  

    mechanism:
      #  ：  +   +  
      - __class__: LinearAdditive

        param:
          - __class__: SignedUniform
            low: 0.5              #  ， 
            high: 2.0

        bias:
          - __class__: Uniform
            low: -1.0
            high: 1.0

        noise:
          - __class__: Gaussian   #  

        noise_scale:              #  
          - __class__: Uniform
            low: 0.5
            high: 1.0

        n_interv_vars: [1.0]
        interv_dist:
          - __class__: SignedUniform
            low: 2.0              #  
            high: 5.0