data:
  - n_observations_obs: null
    n_observations_int: null
    graph:
      - __class__: ErdosRenyi
        edges_per_var: [ 2.0 ]
    mechanism:
      - __class__: LinearAdditive
        param:
          - __class__: SignedUniform
            low: 0.5
            high: 2.0
        bias:
          - __class__: Uniform
            low: -2.0
            high: 2.0
        noise:
          - __class__: Gaussian
        
        noise_scale_heteroscedastic:
          - rff:
            length_scale: 5.0
            output_scale: 1.5

        n_interv_vars: [ 1.0 ]
        interv_dist:
          - __class__: SignedUniform
            low: 1.0
            high: 5.0