data:
  - n_observations_obs: null
    n_observations_int: null
    graph:
      - __class__: ErdosRenyi
        edges_per_var: [ 2.0 ]
    mechanism:
      - __class__: RFFAdditive
        length_scale:
          - __class__: Uniform
            low: 0.5
            high: 1.5
        output_scale:
          - __class__: Uniform
            low: 0.5
            high: 2.0
        bias:
          - __class__: Uniform
            low: -1.0
            high: 1.0
        noise:
          - __class__: Gaussian
        noise_scale:
          - __class__: Uniform
            low: 0.2
            high: 1.0
        n_interv_vars: [ 1.0 ]
        interv_dist:
          - __class__: SignedUniform
            low: 1.0
            high: 3.0